# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   namespace: default
#   name: deployment-2048
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: app-2048
#   replicas: 0
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: app-2048
#     spec:
#       containers:
#       - image: vmalhotra7/2048:latest
#         imagePullPolicy: Always
#         name: app-2048
#         ports:
#         - containerPort: 80