name: build
on:
  push:
    branches:
      - main
  pull_request:


env:
  ENVIRONMENT: "dev"
  PROJECT_DIR: "game-2048-example"
  PROJECT_NAME: "game-2048"

jobs:
  build:
    permissions: write-all
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'C06PTQV0QLW'
          # For posting a simple plain text message
          slack-message: "GitHub build result:"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build an image from Dockerfile
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.PROJECT_DIR }}
          push: true
          tags: "${{ secrets.DOCKER_REGISTRY }}/${{ secrets.PROJECT_NAME }}:latest"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'vmalhotra7/2048:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
